### ISSUE TITLE
Feature request: add support for a specific cache store

### ISSUE THREAD

**Issue by IAmRGroot** [juampi92/artisan-cache-debug#1]
I'm using redis for other cache stores than the default store. Could you maybe add a command option to specify certain cache stores? 

For example `php artisan cache:debug --store=redis` would show the results for the that specific store. 

If I change https://github.com/juampi92/artisan-cache-debug/blob/main/src/CacheExplorerManager.php#L13  to this, it just works as expected for me :+1: 
```php
    private readonly Repository $cacheManager;

    public function __construct() 
    {
        $this->cacheManager = Cache::store('redis');
    }
```

**Comment by juampi92** [comment]
https://github.com/juampi92/artisan-cache-debug/releases/tag/v1.1

Feature added on release v1.1 !
